--- 
- name: playbook to install project sofware tools
  hosts: webservers
  gather_facts: true
  become: true


  tasks:
  - name: install dependencies
    yum:
      name: epel-release
      stme: present
  - name: install nginx
    yum:
      name: nginx
      state: latest